### ISSUE TITLE
stupid question, why need xvfb lib ?

### ISSUE THREAD

**Issue by nvcken** [Endogen/Telegram-TradeOgre-Bot#1]
What is it use for ?

**Comment by Endogen** [comment]
That's not a stupid question at all 😄 

The bot has also the ability to generate a (price) chart for the currently active coin and i use [Plotly](https://plot.ly) to generate the chart. And Plotly needs to have [Orca](https://github.com/plotly/orca) installed to generate the images.

Orca uses the same base as Google Chrome and is basically a desktop app but since you normally would like to run the bot on a linux server without any screen, you have to use `xvfb` that simulates the screen.

It's kind of freaky but there is no other way and in the end it's not as shitty as it feels
